spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

cors:
  origins: http://localhost:5173,http://localhost:3000

server:
  servlet:
    context-path: /venda/api

springdoc:
  swagger-ui:
    path: /public/swagger